// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  'Dashboard': {
    'details': 'Details',
    'home': 'Home',
    'overview': 'Overview',
    'title': 'Dashboard'
  },
  'Deployments': {
    'byCountry': 'Deployments by Country'
  },
  'ErrorPage': {
    'home': 'Back to home',
    'title': 'Oops, something went wrong!',
    'try': 'Try again'
  },
  'Header': {
    'title': 'Hello World'
  },
  'Footer': {
    'copyright': 'Copyright'
  },
  'Login': {
    'email': 'Email',
    'password': 'Password',
    'signIn': 'Sign In'
  }
};
export default messages;